### ISSUE TITLE
Game Tutorial Pop ups

### ISSUE THREAD

**Issue by Gautier404** [uclaacm/selector-safari#15]
On first level, add little textboxes with arrows that explain what the different tools in our game do.

**Comment by reginawang3495** [comment]
Tooltips are nice! There are a lot of npm libraries for it :))

**Comment by Kyle-Pu** [comment]
Thanks! That'll probably work nice with the hex copies. For the first level, I was thinking of using something like [React Joyride](https://github.com/gilbarbara/react-joyride).

**Comment by reginawang3495** [comment]
Ye sounds good! Do you think that having tool tips for copied should be a separate ticket then? @Nhamakami7 @Kyle-Pu

**Comment by Kyle-Pu** [comment]
Yeah, that's a good idea

**Comment by Nhamakami7** [comment]
yea i can make a separate issue for that!
