### ISSUE TITLE
Remove left arrow for level 1

### ISSUE THREAD

**Issue by Nhamakami7** [uclaacm/selector-safari#38]
On the first level, there is left arrow on the top-right. This doesn't need to be there, however, since there aren't any levels before level 1.

<img width="162" alt="image" src="https://user-images.githubusercontent.com/25124783/153958532-40392730-1033-474d-bcc3-7d2018564ac0.png">

**Comment by reginawang3495** [comment]
And arrow right in last level !

**Comment by Nhamakami7** [comment]
Task has been completed.
